language: node_js

cache:
  yarn: true
  
install:
  - yarn install

node_js:
  - "8"
  - "10"

before_script:
  - yarn install
  - npm run bootstrap -- --npm-client=yarn

after_success:
  - npm run coveralls